### ISSUE TITLE
Merging multiple sequencing lane fastq-files

### ISSUE THREAD

**Issue by teekhout** [HuffordLab/Maize_WGS_Build#7]
Hi,

Good job on automating this pipeline through nextflow!
I have several fastq-files of the same sample, sequenced on different sequencing lanes, and I was wondering at what stage these should be merged together.
I tried giving them the same sample name in my reads_file and running the pipeline, but then I get an "input file name collision" error at the run_gatk_snp stage because I have multiple sample_merged.bam files.

Thanks in advance!

Best regards,

Thomas

**Comment by j23414** [comment]
Hi Thomas,

Thank you for using our workflow and providing feedback! 
I was chatting with @aseetharam and I'm guessing your `reads_file` looks similar to:
```
sample1 read-R1_L001.fq.gz read-R2_L001.fq.gz
sample1 read-R1_L002.fq.gz read-R2_L002.fq.gz
sample1 read-R1_L003.fq.gz read-R2_L003.fq.gz
```
I had been naming intermediate files based on the first column ("sample1") which is causing the "input file name collision" error -- my bad. 

We'll fix it in the next few days and get back to you. Thanks for letting us know about the error!

Jennifer

**Comment by j23414** [comment]
Hi Thomas, 

Made the fix, feel free to try it out! Hopefully, this should allow merging multiple sequencing lane fastq-files. 

An example input `reads_file` can still look similar to:
```
sample1 read-R1_L001.fq.gz read-R2_L001.fq.gz
sample1 read-R1_L002.fq.gz read-R2_L002.fq.gz
sample1 read-R1_L003.fq.gz read-R2_L003.fq.gz
```
Definitely post if there are any errors/issues

Best wishes,
Jennifer
